### ISSUE TITLE
扫码提示"为了你的帐号安全，此微信号已不允许登录网页微信。"

### ISSUE THREAD

**Issue by HarrisonQi** [sfyc23/EverydayWechat#128]
`Getting uuid of QR code.
Downloading QR code.
Please scan the QR code to log in.
Please press confirm on your phone.
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登 录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>`

Start auto replying.
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    run()
  File "run.py", line 11, in run
    hongmeng.run()
  File "D:\code\github\EverydayWechat\main\hongmeng.py", line 37, in run
    if not is_online(auto_login=True):
  File "D:\code\github\EverydayWechat\main\hongmeng.py", line 79, in is_online
    itchat.auto_login(hotReload=hotReload, loginCallback=loginCallback, exitCallback=exitCallback)
  File "C:\Users\10361\AppData\Roaming\Python\Python37\site-packages\itchat\components\register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "C:\Users\10361\AppData\Roaming\Python\Python37\site-packages\itchat\components\hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by HarrisonQi** [comment]
原来账号有限制...

**Comment by sfyc23** [comment]
你是发消息太多造成的吗，还是直接用不了。消息太频繁的，几天后就可以了

**Comment by wave2588** [comment]
请问你解决了吗?
