### ISSUE TITLE
python  run.py报错

### ISSUE THREAD

**Issue by 372620040** [sfyc23/EverydayWechat#132]
安装依赖的时候没有报错，但是在python run.py的时候报错了，应该是没有办法下载二维码下来
PS E:\wechat> python run.py
Getting uuid of QR code.
Downloading QR code.
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    run()
  File "run.py", line 12, in run
    main.run()
  File "E:\wechat\everyday_wechat\main.py", line 34, in run
    if not is_online(auto_login=True):
  File "E:\wechat\everyday_wechat\main.py", line 76, in is_online
    itchat.auto_login(hotReload=hotReload, loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\Anaconda3\lib\site-packages\itchat\components\register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "D:\Anaconda3\lib\site-packages\itchat\components\login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "D:\Anaconda3\lib\site-packages\itchat\components\login.py", line 123, in get_QR
    utils.print_qr(picDir)
  File "D:\Anaconda3\lib\site-packages\itchat\utils.py", line 85, in print_qr
    os.startfile(fileDir)
OSError: [WinError 1155] 没有应用程序与此操作的指定文件有关联。: 'QR.png'

**Comment by yu1002139909** [comment]
我也是这个问题

**Comment by sfyc23** [comment]
没有指定默认打开图片的软件吧，

**Comment by crifan** [comment]
之前在回答：
[帮帮孩子，wxpy不会用【抱拳了】-CSDN论坛](https://bbs.csdn.net/topics/395649706?page=1#post-410435691)
时，用google搜
python os.startfile 没有应用程序与此操作的程序有关联
找到了：
[解决Python使用wxpy模块登录微信。就会抛出异常错误。_夏末班车博客-CSDN博客](https://blog.csdn.net/qq_21349669/article/details/78873193)
里面有和此一样的问题，且给出了答案。
帮忙整理如下：

> 打开这个文件
> `C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\itchat\utils.py`
> 导入import webbrowser模块，之后修改这段代码

```python
import webbrowser

def print_qr(fileDir):
    if config.OS == 'Darwin':
        subprocess.call(['open', fileDir])
    elif config.OS == 'Linux':
        subprocess.call(['xdg-open', fileDir])
    elif config.OS == 'Windows':
        #subprocess.call(['cmd', fileDir])
        #os.startfile(fileDir)
        webbrowser.open(fileDir)
    else:
        os.startfile(fileDir)
```

> 然后运行登录代码，即可打开浏览器，然后关闭浏览器，扫描生成的二维码图片即可登录成功。


解释：
看来是让 浏览器 即 webbrowser 去打开上述（QQ.png）的图片。即可省去，windows中非要安装和png图片关联的软件了。
