### ISSUE TITLE
run.py 运行报错

### ISSUE THREAD

**Issue by reginaldZQ** [sfyc23/EverydayWechat#173]
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>Ϊ▒▒▒▒▒▒ʺŰ▒ȫ▒▒▒▒΢▒źŲ▒▒ܵ▒¼▒▒ҳ΢▒š▒▒▒▒▒▒ʹ▒▒Windows΢▒Ż▒Mac΢▒▒▒ڵ▒▒Զ˵▒¼▒▒Windows΢▒▒▒▒▒ص▒ַ▒▒https://pc.weixin.qq.com  Mac΢▒▒▒▒▒ص▒ַ▒▒https://mac.weixin.qq.com</message></error>
Start auto replying.
▒▒▒ݿ▒δ▒▒▒▒▒▒▒▒▒▒ʧ▒▒
Traceback (most recent call last):
  File "run.py", line 67, in <module>
    run()
  File "run.py", line 63, in run
    main.run()
  File "C:\Users\zhangqinhao\Desktop\EverydayWechat-master\everyday_wechat\main.py", line 42, in run
    if not is_online(auto_login=True):
  File "C:\Users\zhangqinhao\Desktop\EverydayWechat-master\everyday_wechat\main.py", line 78, in is_online
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "E:\python36\lib\site-packages\itchat\components\register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "E:\python36\lib\site-packages\itchat\components\hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by reginaldZQ** [comment]
是我的微信被限制了吗。。。  那下面的 keyerror：‘User'是什么意思啊？

**Comment by wangxing1986** [comment]
login失败了，估计被限制登录了。你在浏览器上登录试试

**Comment by reginaldZQ** [comment]
已经被限制了。。。。。。

**Comment by swiftPeter** [comment]
现在老的微信号也没办法登陆了，估计全凉了

**Comment by sfyc23** [comment]
这个问题没有答案，我的微信号中也有登录不了网页微信的。登录不了，这个项目就玩不了。
