### ISSUE TITLE
ModuleNotFoundError: No module named 'apscheduler'

### ISSUE THREAD

**Issue by pptt100** [sfyc23/EverydayWechat#203]
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from  main import hongmeng
  File "F:\project\EverydayWechat-master\main\hongmeng.py", line 10, in <module>

    from apscheduler.schedulers.blocking import BlockingScheduler
ModuleNotFoundError: No module named 'apscheduler'
这个该怎么办？没有找到apscheduler在哪个文件

**Comment by Witte-hang** [comment]
pip install this packgae
