### ISSUE TITLE
发消息提示ValueError: time data ' ' does not match format '%Y-%m-%d'

### ISSUE THREAD

**Issue by xhily** [sfyc23/EverydayWechat#21]
登录成功
**************************************************
获取相关信息...
获取格言信息..
获取天气信息..
Job "gfweather.start_today_info (trigger: cron[hour='0', minute='57'], next run at: 2019-06-08 00:57:00 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\EverydayWechat-master\GFWeather.py", line 141, in start_today_info
    sweet_words=sweet_words)
  File "D:\EverydayWechat-master\GFWeather.py", line 233, in get_weather_info
    start_datetime = datetime.strptime(start_date, "%Y-%m-%d")
  File "C:\Python\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Python\Python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data ' ' does not match format '%Y-%m-%d'

**Comment by xhily** [comment]
找到问题了  日期不能空格 要空

**Comment by sfyc23** [comment]
我之后再做一下非空&日期错误的验证吧。
