### ISSUE TITLE
老哥我是小白可以帮我看看不

### ISSUE THREAD

**Issue by Jasonandy** [sfyc23/EverydayWechat#4]
D:\devtools\Python38\python.exe E:/PyCharmSpace/Python-X/cn/love/GFWeather.py
Traceback (most recent call last):
  File "E:/PyCharmSpace/Python-X/cn/love/GFWeather.py", line 247, in <module>
    gfweather().start_today_info(True)
  File "E:/PyCharmSpace/Python-X/cn/love/GFWeather.py", line 20, in __init__
    self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
  File "E:/PyCharmSpace/Python-X/cn/love/GFWeather.py", line 28, in get_init_data
    config = load(f, loader=yaml.FullLoader)
TypeError: load() got an unexpected keyword argument 'loader'

**Comment by Jasonandy** [comment]
弄好了 感谢 那个yaml load我搞错了 谢谢老哥
