### ISSUE TITLE
ModuleNotFoundError: No module named 'itchat'

### ISSUE THREAD

**Issue by mackyuqimack** [sfyc23/EverydayWechat#50]
Traceback (most recent call last):
  File "D:/PycharmProjects/EverydayWechat/run.py", line 1, in <module>
    from GFWeather import GFWeather
  File "D:\PycharmProjects\EverydayWechat\GFWeather.py", line 5, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'

我是一个python新人，请问报这个错该怎么处理呀，能下的包我都下了的

**Comment by sfyc23** [comment]
先用 pip install -r requirements.txt  安装这些库。

**Comment by Doslin** [comment]
我安装了这些库，也没有用
```[root@VM_0_9_centos EverydayWechat]# python run.py
  File "run.py", line 6
SyntaxError: Non-ASCII character '\xe4' in file run.py on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[root@VM_0_9_centos EverydayWechat]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from GFWeather import GFWeather
  File "/root/EverydayWechat/GFWeather.py", line 5, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'
[root@VM_0_9_centos EverydayWechat]#  pip install -r requirements.txt 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: https://pypi.doubanio.com/simple
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (4.7.1)
Requirement already satisfied: itchat in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.3.10)
Requirement already satisfied: apscheduler in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 4)) (3.6.0)
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 5)) (3.10)
Requirement already satisfied: lxml in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 6)) (4.3.3)
Requirement already satisfied: soupsieve>=1.2 in /usr/lib/python2.7/site-packages (from beautifulsoup4->-r requirements.txt (line 2)) (1.9.1)
Requirement already satisfied: pyqrcode in /usr/lib/python2.7/site-packages (from itchat->-r requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: pypng in /usr/lib/python2.7/site-packages (from itchat->-r requirements.txt (line 3)) (0.0.19)
Requirement already satisfied: funcsigs; python_version == "2.7" in /usr/lib/python2.7/site-packages (from apscheduler->-r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python2.7/site-packages (from apscheduler->-r requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python2.7/site-packages (from apscheduler->-r requirements.txt (line 4)) (41.0.1)
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from apscheduler->-r requirements.txt (line 4)) (2019.1)
Requirement already satisfied: tzlocal>=1.2 in /usr/lib/python2.7/site-packages (from apscheduler->-r requirements.txt (line 4)) (1.5.1)
Requirement already satisfied: futures; python_version == "2.7" in /usr/lib/python2.7/site-packages (from apscheduler->-r requirements.txt (line 4)) (3.2.0)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/lib/python2.7/site-packages (from soupsieve>=1.2->beautifulsoup4->-r requirements.txt (line 2)) (1.5)
[root@VM_0_9_centos EverydayWechat]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from GFWeather import GFWeather
  File "/root/EverydayWechat/GFWeather.py", line 5, in <module>
    import itchat
ModuleNotFoundError: No module named 'itchat'
[root@VM_0_9_centos EverydayWechat]#

**Comment by Doslin** [comment]
我用 pip3 install -r requirements.txt实现了好了
如果你没有pip3 ，那就需要安装pip
#### 安装pip
方法一.python3安装完成后默认已经带有pip3

你可以用以下命令,创建软链接
`ln -s /usr/Python-3.6/bin/pip3 /usr/bin/pip3`
方法二.使用以下方法重新安装pip插件
下载get-pip.py脚本
`wget https://bootstrap.pypa.io/3.2/get-pip.py`

运行脚本
`python3 get-pip.py`

python3创建pip3索引
ln -s /usr/python3.6.1/bin/pip /usr/bin/pip3
