### ISSUE TITLE
想请问下，出现了一个bug，你看看咋回事

### ISSUE THREAD

**Issue by Nono17** [sfyc23/EverydayWechat#68]
"expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "_config.yaml", line 6, column 1
expected <block end>, but found '<scalar>'
  in "_config.yaml", line 25, column 2

**Comment by chen366690712** [comment]
不是提示出那行出错么？配置贴一下？

**Comment by Nono17** [comment]
> 不是提示出那行出错么？配置贴一下？

Traceback (most recent call last):
  File "D:/program/EverydayWechat/run.py", line 21, in <module>
    run()
  File "D:/program/EverydayWechat/run.py", line 9, in run
    GFWeather().run()
  File "D:\program\EverydayWechat\GFWeather.py", line 21, in __init__
    self.girlfriend_list, self.alarm_hour, self.alarm_minute, self.dictum_channel = self.get_init_data()
  File "D:\program\EverydayWechat\GFWeather.py", line 29, in get_init_data
    config = yaml.load(f, Loader=yaml.Loader)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\yaml\parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "_config.yaml", line 6, column 1
expected <block end>, but found '<scalar>'
  in "_config.yaml", line 25, column 2

详细信息是这个，但是不太明白yaml文件哪出错了

**Comment by sfyc23** [comment]
应该是你的 yaml 配置文件出错了。你看一下 yaml 的语法。
