### ISSUE TITLE
ubuntu运行半天，先是xopen错误，后是KeyError: 'User'

### ISSUE THREAD

**Issue by johnsonliu33** [sfyc23/EverydayWechat#70]
ubuntu运行半天，先是xopen错误，后是KeyError: 'User',好气

**Comment by sfyc23** [comment]
能把错误信息粘出来吗，你这么说，我也不清楚是什么问题啊。

**Comment by kingguan4** [comment]
错误代码是这个
Traceback (most recent call last):
  File "F:/design/crown/EverydayWechat-master/run.py", line 22, in <module>
    run()
  File "F:/design/crown/EverydayWechat-master/run.py", line 11, in run
    GFWeather().run()
  File "F:\design\crown\EverydayWechat-master\GFWeather.py", line 121, in run
    if not self.is_online(auto_login=True):
  File "F:\design\crown\EverydayWechat-master\GFWeather.py", line 107, in is_online
    itchat.auto_login(hotReload=True)
  File "F:\Anaconda3\envs\learn\lib\site-packages\itchat\components\register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "F:\Anaconda3\envs\learn\lib\site-packages\itchat\components\hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by sfyc23** [comment]
这个应该 itchat 的版本问题，升级一下版本。
