### ISSUE TITLE
在本地可以跑通在服务器出现不了登录二维码 直接抛错

### ISSUE THREAD

**Issue by 1157987916** [sfyc23/EverydayWechat#77]
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    run()
  File "run.py", line 11, in run
    GFWeather().run()
  File "/root/EverydayWechat/GFWeather.py", line 121, in run
    if not self.is_online(auto_login=True):
  File "/root/EverydayWechat/GFWeather.py", line 107, in is_online
    itchat.auto_login(hotReload=True)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 49, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/components/login.py", line 123, in get_QR
    utils.print_qr(picDir)
  File "/usr/local/python3/lib/python3.6/site-packages/itchat/utils.py", line 83, in print_qr
    subprocess.call(['xdg-open', fileDir])
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open': 'xdg-open'

**Comment by sfyc23** [comment]
你试试网页端微信: https://wx.qq.com/ 你能登录吗。

**Comment by iamsxm** [comment]
apt install xdg-utils
应该要安装一个工具包

**Comment by klgentle** [comment]
Getting uuid of QR code.
Downloading QR code.
Error: no "view" mailcap rules found for type "image/png"
Can't call method "get_value" on an undefined value at /usr/bin/mimeopen line 162.
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 468: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'QR.png'
Please scan the QR code to log in.
Log in time out, reloading QR code.
Getting uuid of QR code.
Downloading QR code.
