### ISSUE TITLE
直接运行run出错

### ISSUE THREAD

**Issue by WindZu** [sfyc23/EverydayWechat#78]
Traceback (most recent call last):
  File ".\run.py", line 22, in <module>
    run()
  File ".\run.py", line 11, in run
    GFWeather().run()
  File "E:\EverydayWechat-master\GFWeather.py", line 121, in run
    if not self.is_online(auto_login=True):
  File "E:\EverydayWechat-master\GFWeather.py", line 107, in is_online
    itchat.auto_login(hotReload=True)
  File "C:\Python37\lib\site-packages\itchat\components\register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "C:\Python37\lib\site-packages\itchat\components\hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by sfyc23** [comment]
你先试试能登录网页微信吗。

**Comment by WindZu** [comment]
@sfyc23 不出现二维码 直接报错

**Comment by sfyc23** [comment]
我是说：你试试在浏览器中，打开网页端微信: https://wx.qq.com/ ，能登录这个微信号吗。

**Comment by WindZu** [comment]
@sfyc23 谢谢作者啦 我找到问题了 我的那个小号是不可以登录网页端的 而我第一次测试的时候是使用的小号 我查看了itchat.auto_login()的说明，其执行的时候会生成一个记录文件，而我后面每次测试的时候报错的都是这个记录文件的错误，把文件删掉再使用可以登录网页端的微信号就ok了
