### ISSUE TITLE
验证码出来了  还没扫直接报错

### ISSUE THREAD

**Issue by 1157987916** [sfyc23/EverydayWechat#79]
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    run()
  File "run.py", line 11, in run
    GFWeather().run()
  File "/root/EverydayWechat/GFWeather.py", line 121, in run
    if not self.is_online(auto_login=True):
  File "/root/EverydayWechat/GFWeather.py", line 107, in is_online
    itchat.auto_login(hotReload=True)
  File "/root/Envs/love/lib/python3.6/site-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/root/Envs/love/lib/python3.6/site-packages/itchat/components/login.py", line 50, in login
    picDir=picDir, qrCallback=qrCallback)
  File "/root/Envs/love/lib/python3.6/site-packages/itchat/components/login.py", line 115, in get_QR
    qrCode.png(qrStorage, scale=10)
AttributeError: 'NoneType' object has no attribute 'png'

**Comment by sfyc23** [comment]
应该是你的微信不能使用网页微信。
