### ISSUE TITLE
错误提示KeyError: 'User'

### ISSUE THREAD

**Issue by kingguan4** [sfyc23/EverydayWechat#89]
Traceback (most recent call last):
  File "F:/design/crown/EverydayWechat-master/run.py", line 22, in <module>
    run()
  File "F:/design/crown/EverydayWechat-master/run.py", line 11, in run
    GFWeather().run()
  File "F:\design\crown\EverydayWechat-master\GFWeather.py", line 121, in run
    if not self.is_online(auto_login=True):
  File "F:\design\crown\EverydayWechat-master\GFWeather.py", line 107, in is_online
    itchat.auto_login(hotReload=True)
  File "F:\Anaconda3\envs\learn\lib\site-packages\itchat\components\register.py", line 29, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback):
  File "F:\Anaconda3\envs\learn\lib\site-packages\itchat\components\hotreload.py", line 54, in load_login_status
    self.loginInfo['User'] = templates.User(self.loginInfo['User'])
KeyError: 'User'

**Comment by sfyc23** [comment]
有可能是你的这个微信有限制，你试试登录网页版微信，看是否成功。或者你换一个号试试。
